@baseUrl = http://localhost:3333

# create user
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Bruno",
  "email": "john@email.com",
  "password": "123456"
}

###
POST {{baseUrl}}/sessions/password
Content-Type: application/json

{
  "email": "john@email.com",
  "password": "123456"
}